services:
    app.serializer.normalizer.custom_object.abstract:
        abstract: true
        public: false
        class: AppBundle\Serializer\Normalizer\CustomObjectNormalizer
        autowire: true

    app.serializer.normalizer.presupuesto:
        parent: "app.serializer.normalizer.custom_object.abstract"
        class: AppBundle\Serializer\Normalizer\PresupuestoNormalizer
        tags:
            - { name: serializer.normalizer }

    app.serializer.normalizer.descripcion:
        parent: "app.serializer.normalizer.custom_object.abstract"
        class: AppBundle\Serializer\Normalizer\DescripcionPresupuestoNormalizer
        tags:
            - { name: serializer.normalizer }
