manosdeobra_listado:
    pattern:  /{page}/{description}
    defaults:
        _controller: PresupuestoBundle:ManoDeObra:listado
        page: 1
        description: 
    requirements:
        page: \d+
        
manosdeobra_agregar:
    pattern:  /agregar
    defaults: { _controller: PresupuestoBundle:ManoDeObra:agregar }
    
manosdeobra_editar:
    pattern:  /editar/{id}
    defaults: { _controller: PresupuestoBundle:ManoDeObra:editar }
    requirements:
        id: \d+

manosdeobra_all_modal:
    pattern:  /todas
    defaults: { _controller: PresupuestoBundle:ManoDeObra:getAll }
    
manosdeobra_all_json:
    pattern:  /json
    defaults: { _controller: PresupuestoBundle:ManoDeObra:json }
    
manosdeobra_get_materiales:
    pattern:  /materiales/{id}
    defaults: { _controller: PresupuestoBundle:ManoDeObra:getMateriales }
    options:
        expose: true