parameters:
#    presupuesto.example.class: AppBundle\Example

services:
#    presupuesto.example:
#        class: %presupuesto.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    k2_view_selector:
        class: AppBundle\Service\ViewSelector
        arguments: 
            - "@service_container"
            
    k2_twig_extensions:
        class: AppBundle\Twig\PresupuestoExtension
        tags:
          - {name: twig.extension}
          
    presupuesto.abstract_manager:
        abstract: true
        calls:
            - [setEm, [@doctrine.orm.entity_manager]]
            - [setFormFactory, [@form.factory]]
          
    presupuesto.manodeobra_manager:
        parent: presupuesto.abstract_manager 
        class: AppBundle\Model\ManoDeObraManager
        arguments:
            - PresupuestoBundle:ManosDeObra
          
    presupuesto.material_manager:
        parent: presupuesto.abstract_manager 
        class: AppBundle\Model\MaterialManager
        arguments:
            - PresupuestoBundle:Material
          
    presupuesto.manager:
        parent: presupuesto.abstract_manager 
        class: AppBundle\Model\PresupuestoManager
        arguments:
            - PresupuestoBundle:Presupuestos

    presupuesto.form:
        class: AppBundle\Form\PresupuestoForm
        tags:
          - {name: form.type, alias: presupuesto}
        arguments:
            - @doctrine.orm.entity_manager
#            - @jms_serializer
          